---
title: "rducklake"
author: "Frank Popham"
format: gfm
eval: false
echo: true
---

rducklake runs a [ducklake](https://ducklake.select/) from R. It is an alternative to the excellent [ducklake-r](https://tgerke.github.io/ducklake-r/).


## Installation

You can install the development version of rducklake from [GitHub](https://github.com/)

```{r}
# install.packages("pak")
pak::pak("frankpopham/rducklake")
```

## Create a ducklake 

```{r}
library(rducklake)

# Make a duckdb connection and database (default is memory - in RAM)

my_con <- connect_duckdb() 

# Create a basic new ducklake with no encryption in the working directory

attach_ducklake(my_con,
                ducklake_filename = "example.ducklake",
                ducklake_alias = "my_ducklake",
                create_if_not_exists = TRUE,
                read_only = FALSE,
                ducklake_type = "duckdb",
                ducklake_encrypt = FALSE,
                parquet_encrypt = FALSE,
                parquet_directory= "data_files")

# See attached databases (the default is now my_ducklake)

attached_databases(my_con)

default_database(my_con)

# Write data to ducklake

library(DBI)

dbWriteTable(my_con, "mtcars", mtcars)

# See record of ducklake commits so far

ducklake_snapshots(my_con, "my_ducklake")

# Detach from ducklake and make memory default database

detach_ducklake(my_con, "my_ducklake", "memory")

# Close connection

disconnect_duckdb(my_con)

```

# Attach to an exisitng ducklake

```{r}
library(rducklake)

# Make a duckdb connection and database (default is memory - in RAM)

my_con <- connect_duckdb() 

# Attach to an existing ducklake and make it the default database

attach_ducklake(my_con,
                ducklake_filename = "example.ducklake",
                ducklake_alias = "my_ducklake",
                ducklake_encrypt = FALSE)

# List tables in ducklake

ducklake_table_info(my_con, "my_ducklake")

# Read into R

library(DBI)

mtcars_from_ducklake <- dbReadTable(my_con, "mtcars")

# Detach from ducklake and make memory default database

detach_ducklake(my_con, "my_ducklake", "memory")

# Close connection

disconnect_duckdb(my_con)


```

